Barber/Models/Appoint.cs
using System.ComponentModel.DataAnnotations;

namespace Barber.Models
{
    public class Appoint
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int PhoneNumber { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        public TimeSpan Time { get; set; }
    }
}

Barber/Models/ErrorViewModel.cs
namespace Barber.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Barber/Controllers/AppointsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Barber.Data;
using Barber.Models;

namespace Barber.Controllers
{
    public class AppointsController : Controller
    {
        private readonly BarberContext _context;

        public AppointsController(BarberContext context)
        {
            _context = context;
        }

        // GET: Appoints
        public async Task<IActionResult> Index()
        {
              return _context.Appoint != null ? 
                          View(await _context.Appoint.ToListAsync()) :
                          Problem("Entity set 'BarberContext.Appoint'  is null.");
        }

        public IActionResult Check()
        {
            return View();
        }

        public async Task<IActionResult> CheckAvaibility(DateTime? Date) 
        {
            if (Date == null || _context.Appoint == null)
            {
                ViewData["results"] = "";
                return View(null);
              
            }
            
            var appoints = await _context.Appoint
                .Where(m => m.Date == Date).ToListAsync();
            if (appoints.Count == 0)
            {
                ViewData["results"] = null;
                return View(null);
            }
           
            ViewData["results"] = appoints;
            return View(appoints);
        }

        // GET: Appoints/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Appoint == null)
            {
                return NotFound();
            }

            var appoint = await _context.Appoint
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appoint == null)
            {
                return NotFound();
            }

            return View(appoint);
        }

        // GET: Appoints/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Appoints/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,PhoneNumber,Date,Time")] Appoint appoint)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appoint);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(appoint);
        }

        // GET: Appoints/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Appoint == null)
            {
                return NotFound();
            }

            var appoint = await _context.Appoint.FindAsync(id);
            if (appoint == null)
            {
                return NotFound();
            }
            return View(appoint);
        }

        // POST: Appoints/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,PhoneNumber,Date,Time")] Appoint appoint)
        {
            if (id != appoint.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appoint);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointExists(appoint.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appoint);
        }

        // GET: Appoints/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Appoint == null)
            {
                return NotFound();
            }

            var appoint = await _context.Appoint
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appoint == null)
            {
                return NotFound();
            }

            return View(appoint);
        }

        // POST: Appoints/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Appoint == null)
            {
                return Problem("Entity set 'BarberContext.Appoint'  is null.");
            }
            var appoint = await _context.Appoint.FindAsync(id);
            if (appoint != null)
            {
                _context.Appoint.Remove(appoint);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointExists(int id)
        {
          return (_context.Appoint?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Barber/Controllers/HomeController.cs
using Barber.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Barber.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Barber/Views/Appoints/CheckAvaibility.cshtml
@model IEnumerable<Barber.Models.Appoint>
@{
    ViewData["Title"] = "Check Avaibility";
}
<h1> Check Availaibility</h1><br />
    <div> 
        
   @ViewData["results"]
        <form action="CheckAvaibility" >
            <table>
               
                <tr>
                     <td>Enter Your Number &nbsp;  </td>
                     
                    <td colspan="2">
                       
                      <input type="date"  class="btn btn-primary" name="Date" /> &nbsp;
                       
                       <input type="submit" value="Submit" class="btn btn-primary" />  
                      
                    </td>
                </tr>

            </table>
            <br />
        
        @if ((IEnumerable<Barber.Models.Appoint>)ViewData["results"] != null)

        {
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PhoneNumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Date)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Time)
                        </th>

                        <th>
                            Status
                        </th>
                    </tr>
                </thead>
                @foreach (var item in (IEnumerable<Barber.Models.Appoint>)ViewData["results"])
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Time)
                        </td>
                        <td> Booked</td>
                    </tr>
                }

            </table>
        }
        else 
        {
            if( ViewData["results"] == null)
            {
                
                <p>No match found </p>
            }
            

        }
    </form>
        </div>
         <div>
   <a asp-controller="Appoints" asp-action="Index"><input type="submit" value=" Create Appointment" class="btn btn-primary" /> </a>
</div>

Barber/Views/Appoints/Create.cshtml
@model Barber.Models.Appoint

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Appoint</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" type="time" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Barber/Views/Appoints/Delete.cshtml
@model Barber.Models.Appoint

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appoint</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Barber/Views/Appoints/Details.cshtml
@model Barber.Models.Appoint

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Appoint</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Barber/Views/Appoints/Edit.cshtml
@model Barber.Models.Appoint

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Appoint</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Barber/Views/Appoints/Index.cshtml
@model IEnumerable<Barber.Models.Appoint>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Barber/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Barber/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Barber</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Barber.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Barber</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appoints" asp-action="Index">Appoint</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appoints" asp-action="CheckAvaibility">Check Avaibility</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Barber - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>